//////MOCK DATA////////
export const FOUNDATION_PROGRAMS = [
  "Finance",
  "Art & Design",
  "Business",
  "Engineering",
  "Management",
  "Socila Science & Pharmacy",
  "Computing",
  "Media",
  "Law",
  "Humanities",
];
export const BACHELORS_PROGRAMS = [
  "B. com",
  "B.Sc - Nursing",
  "B.Sc - Nursing",
  "B.Sc - Interior Design",
  "B.Tech",
  "BDS - Bachelor of Dental Surgery",
  "B.Sc",
];
export const MASTERS_PROGRAMS = [
  "Master of Arts (MA)",
  "Master of Business Administration (MBA)",
  "Master of Science (MS, MSc)",
  "Master of Library Science (MLS, MLIS, MSLS)",
  "Master of Research (MRes)",
  "Master of Public Administration",
  "Master by Research (MPhil)",
];
export const PHD_PROGRAMS = [
  "Physics",
  "Art & Design",
  "Chemistry",
  "Clinical Research",
  "Mathematics",
  "Social Work",
  "BioSciences",
  "Literature",
];

export const MOCK_DATA = [
  {
    month: "Jan",
    students: 5,
    agents: 13,
    universities: 1,
    revenueFromStudents: 12,
    revenueFromUniversities: 142,
    revenueFromAgents: 12442,
  },
  {
    month: "Feb",
    students: 75,
    agents: 24,
    universities: 1,
    revenueFromStudents: 442,
    revenueFromUniversities: 300,
    revenueFromAgents: 12442,
  },
  {
    month: "Mar",
    students: 135,
    agents: 60,
    universities: 1,
    revenueFromStudents: 240,
    revenueFromUniversities: 320,
    revenueFromAgents: 12442,
  },
  {
    month: "Apr",
    students: 100,
    agents: 15,
    universities: 1,
    revenueFromStudents: 650,
    revenueFromUniversities: 580,
    revenueFromAgents: 12442,
  },
  {
    month: "May",
    students: 150,
    agents: 30,
    universities: 1,
    revenueFromStudents: 230,
    revenueFromUniversities: 550,
    revenueFromAgents: 12442,
  },
  {
    month: "Jun",
    students: 175,
    agents: 120,
    universities: 1,
    revenueFromStudents: 300,
    revenueFromUniversities: 650,
    revenueFromAgents: 12442,
  },
  {
    month: "Jul",
    students: 300,
    agents: 90,
    universities: 1,
    revenueFromStudents: 340,
    revenueFromUniversities: 550,
    revenueFromAgents: 12442,
  },
  {
    month: "Aug",
    students: 190,
    agents: 60,
    universities: 1,
    revenueFromStudents: 750,
    revenueFromUniversities: 790,
    revenueFromAgents: 12442,
  },
  {
    month: "Sep",
    students: 60,
    agents: 80,
    universities: 1,
    revenueFromStudents: 399,
    revenueFromUniversities: 482,
    revenueFromAgents: 12442,
  },
  {
    month: "Oct",
    students: 235,
    agents: 100,
    universities: 1,
    revenueFromStudents: 289,
    revenueFromUniversities: 389,
    revenueFromAgents: 12442,
  },
  {
    month: "Nov",
    students: 190,
    agents: 120,
    universities: 1,
    revenueFromStudents: 199,
    revenueFromUniversities: 174,
    revenueFromAgents: 12442,
  },
  {
    month: "Dec",
    students: 100,
    agents: 40,
    universities: 1,
    revenueFromStudents: 432,
    revenueFromUniversities: 369,
    revenueFromAgents: 12442,
  },
];

export const STUDENTS_LIST = [
  {
    name: "Fahad Farooqi",
    email: "fahadfarooqi@gmail.com",
    phoneNumber: "+92 306 5555523",
    nationality: "Pakistan",
    education: "3 Year Bechelors",
    testScore: "IELTS : 8.3 (17/05/2022)",
    destination: "Australia(Sydney)",
    id: "#1256478",
  },

  {
    name: "Fanie Rathod",
    email: "fanierathod@gmail.com",
    phoneNumber: "+92 516 5555523",
    nationality: "Indian",
    education: "Master Degree",
    testScore: "IELTS : 7.3 (17/05/2022)",
    destination: "Australia(Melbourne )",
    id: "#12578",
  },

  {
    name: "Flora Smith",
    email: "florasmith@gmail.com",
    phoneNumber: "+92 306 5555523",
    nationality: "Australia",
    education: "3 Year Bechelors",
    testScore: "IELTS : 8.3 (17/05/2022)",
    destination: "Australia(Adelaide)",
    id: "#56478",
  },

  {
    name: "Faith Jonas",
    email: "faithjonas@gmail.com",
    phoneNumber: "+92 306 5555523",
    nationality: "USA",
    education: "3 Year Bechelors",
    testScore: "IELTS : 8.3 (17/05/2022)",
    destination: "Australia(Canberra) ",
    id: "#125647",
  },

  {
    name: "Fahad Farooqi",
    email: "fahadfarooqi@gmail.com",
    phoneNumber: "+92 306 5555523",
    nationality: "Pakistan",
    education: "3 Year Bechelors",
    testScore: "IELTS : 8.3 (17/05/2022)",
    destination: "Australia(Sydney)",
    id: "#11256478",
  },

  {
    name: "Fanie Rathod",
    email: "fanierathod@gmail.com",
    phoneNumber: "+92 516 5555523",
    nationality: "Indian",
    education: "Master Degree",
    testScore: "IELTS : 7.3 (17/05/2022)",
    destination: "Australia(Melbourne )",
    id: "#122578",
  },

  {
    name: "Flora Smith",
    email: "florasmith@gmail.com",
    phoneNumber: "+92 306 5555523",
    nationality: "Australia",
    education: "3 Year Bechelors",
    testScore: "IELTS : 8.3 (17/05/2022)",
    destination: "Australia(Adelaide)",
    id: "#536478",
  },

  {
    name: "Faith Jonas",
    email: "faithjonas@gmail.com",
    phoneNumber: "+92 306 5555523",
    nationality: "USA",
    education: "3 Year Bechelors",
    testScore: "IELTS : 8.3 (17/05/2022)",
    destination: "Australia(Canberra) ",
    id: "#1254647",
  },
];

export const notifications = [
  {
    id: 123,
    title: "XYZ University Graduation Ceremony",
    date: "2023-02-27T10:30:00Z",
    body: "Dear all, you are cordially invited to attend John Doe's graduation ceremony at XYZ University on June 5th, 2023 at 10:00 AM. Please RSVP by May 15th. We hope to see you there!",
    photo: "https://picsum.photos/id/11/200/300",
  },
  {
    id: 3,
    title: "Adrian Roy",
    date: "2023-02-25T16:12:00Z",
    body: "Adrian submitted the application",
    photo: "https://picsum.photos/id/30/200/300",
  },
  {
    id: 4,
    title: "Scholarship Application Deadline Approaching",
    date: "2023-02-15T09:45:00Z",
    body: "Dear students, this is a reminder that the deadline for scholarship applications is approaching. If you haven't submitted your application yet, please do so as soon as possible. Scholarships are awarded based on academic merit and financial need, so make sure to include all relevant information in your application. Good luck!",
    photo: "https://picsum.photos/id/40/200/300",
  },
  {
    id: 2,
    title: "Changes in Course Schedule",
    date: "2023-02-15T06:15:00Z",
    body: "Dear students, please be advised that there have been changes in the course schedule for the upcoming semester. The updated schedule is now available on the university's website. Please review it carefully and make the necessary adjustments to your personal schedules. If you have any questions or concerns, please don't hesitate to contact your academic advisor. Thank you.",
    photo: "https://picsum.photos/id/20/200/300",
  },
  {
    id: 43,
    title: "Ajuma jaine",
    date: "2023-02-14T16:12:00Z",
    body: "Ajuma jaine submitted the application",
    photo: "https://picsum.photos/id/310/200/300",
  },
  {
    id: 5,
    title: "Guest Speaker at Lecture Series",
    date: "2023-02-20T11:12:00Z",
    body: "Dear students and faculty, we are pleased to announce that Dr. Jane Smith, a renowned expert in her field, will be our guest speaker at the next lecture series. Dr. Smith will be discussing her latest research on the effects of climate change on marine ecosystems. The lecture will take place on September 20th, 2023 at 2:00 PM in the university's lecture hall. We hope to see you there!",
    photo: "https://picsum.photos/id/50/200/300",
  },
  {
    id: 1,
    title: "XYZ University Graduation Ceremony",
    date: "2023-02-05T10:30:00Z",
    body: "Dear all, you are cordially invited to attend John Doe's graduation ceremony at XYZ University on June 5th, 2023 at 10:00 AM. Please RSVP by May 15th. We hope to see you there!",
    photo: "https://picsum.photos/id/10/200/300",
  },
  {
    id: 2,
    title: "Changes in Course Schedule",
    date: "2023-02-15T06:01:00Z",
    body: "Dear students, please be advised that there have been changes in the course schedule for the upcoming semester. The updated schedule is now available on the university's website. Please review it carefully and make the necessary adjustments to your personal schedules. If you have any questions or concerns, please don't hesitate to contact your academic advisor. Thank you.",
    photo: "https://picsum.photos/id/20/200/300",
  },
];
